完善相关文档
ishkong/go-cqhttp-docs pull request #109
Opened 2023-01-13 07:45 UTC by SlimeNull

2023-01-13 15:09 UTC, ishkong commented
管理API在 v1.0.0-beta1 版本被移除 
https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-beta1

2023-01-13 15:09 UTC, ishkong requested changes
移除关于管理API部分内容

2023-01-14 16:27 UTC, SlimeNull commented
第一次见到 Changes request 呜呜呜, 还是问了朋友之后才知道, 直接继续提交并推送就可以 (

2023-01-15 00:48 UTC, SlimeNull commented
疯狂更新文档ing (都是亲手测试的呜呜呜

2023-01-15 00:48 UTC, SlimeNull commented
有趣捏
![image](https://user-images.githubusercontent.com/69663231/212503462-61755d60-bfa6-4495-ae36-8308eba62b10.png)

2023-01-15 00:55 UTC, SlimeNull commented
话说仓库主, 那个 message_id 的问题, 你看没看呀, 如果 message_id 确实是 int32, 我就把所有接口参数说明全都改成 int32, 如果是 int64 我就去改成 int64 了, 现在完全都不统一来着 (っ °Д °;)っ

2023-01-15 02:44 UTC, SlimeNull commented
咕咕咕, 肝了一晚上 (玩了一晚上
文档 + go-cqhttp 的 SDK 两边都在写 ( •̀ ω •́ )y

2023-01-15 02:56 UTC, SlimeNull commented
困死了, 睡觉去了 (

2023-01-16 02:47 UTC, ishkong approved these changes

2023-01-16 02:47 UTC, merged