✨在Post_Type加入遗漏内容`message_sent`
ishkong/go-cqhttp-docs pull request #124
Opened 2023-02-20 15:20 UTC by HsiangNianian

2023-02-22 01:11 UTC, SlimeNull reviewed
如果真的有这个上报的话, 建议也在文档中补充上报数据

2023-02-22 01:43 UTC, ishkong requested changes

2023-02-22 01:43 UTC, ishkong commented on docs/reference/data_struct.md
> +| message_sent | 消息发送，例如，bot发送在群里的消息|
这个在 master 中并没有发现，麻烦提供一下，在哪里会出现这个

2023-04-04 13:33 UTC, Zaitonn commented on docs/reference/data_struct.md
> +| message_sent | 消息发送，例如，bot发送在群里的消息|
```yml
message:
  # 是否上报自身消息
  report-self-message: true
```
貌似这样收到自身发出的消息就是`message_sent`

https://github.com/Mrs4s/go-cqhttp/blob/749cde2a6dc2ebed6d4f2bb5517763752e48f44c/coolq/event.go#L42-L49C26

2023-06-03 02:12 UTC, ishkong approved these changes

2023-06-03 02:12 UTC, ishkong commented on docs/reference/data_struct.md
> +| message_sent | 消息发送，例如，bot发送在群里的消息|
好的

2023-06-03 02:12 UTC, merged