添加sdk
ishkong/go-cqhttp-docs pull request #130
Opened 2023-04-22 15:21 UTC by quqi2

2023-04-23 01:30 UTC, ishkong requested changes

2023-04-23 01:30 UTC, ishkong commented on docs/guide/quick_start.md
> +| GO | Nyabot | NyaBot 是一个基于 Go 语言的开源聊天机器人框架，支持多种聊天平台协议。| 正向 HTTP, 正反向 WebSocket | [GitHub](https://github.com/Elyart-Network/NyaBot)
统一一下，把这个放在上面那个GO下面吧

2023-04-24 11:20 UTC, quqi2 commented
改了

2023-06-03 02:11 UTC, ishkong approved these changes

2023-06-03 02:11 UTC, merged